### ISSUE TITLE
NGINX container fails to start

### ISSUE THREAD

**Issue by gabemarshall** [thinkst/canarytokens-docker#1]
I'm getting the following in my docker logs when running docker-compose up 

Ubuntu 14.10

```
frontend_1    | Failed to load application:
frontend_1    |
frontend_1    | [x] Adding domains
frontend_1    | 	<redacted>.com
frontend_1    | [x] Adding NX domains
frontend_1    | Unhandled Error
frontend_1    | Traceback (most recent call last):
frontend_1    |   File "/usr/local/lib/python2.7/site-packages/twisted/application/app.py", line 657, in run
frontend_1    |     runApp(config)
frontend_1    |   File "/usr/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 23, in runApp
frontend_1    |     _SomeApplicationRunner(config).run()
frontend_1    |   File "/usr/local/lib/python2.7/site-packages/twisted/application/app.py", line 389, in run
frontend_1    |     self.application = self.createOrGetApplication()
frontend_1    |   File "/usr/local/lib/python2.7/site-packages/twisted/application/app.py", line 454, in createOrGetApplication
frontend_1    |     application = getApplication(self.config, passphrase)
frontend_1    | --- <exception caught here> ---
frontend_1    |   File "/usr/local/lib/python2.7/site-packages/twisted/application/app.py", line 465, in getApplication
frontend_1    |     application = service.loadApplication(filename, style, passphrase)
frontend_1    |   File "/usr/local/lib/python2.7/site-packages/twisted/application/service.py", line 403, in loadApplication
frontend_1    |     application = sob.loadValueFromFile(filename, 'application', passphrase)
frontend_1    |   File "/usr/local/lib/python2.7/site-packages/twisted/persisted/sob.py", line 210, in loadValueFromFile
frontend_1    |     exec fileObj in d, d
frontend_1    |   File "frontend.tac", line 11, in <module>
frontend_1    |     import setup_db
frontend_1    |   File "/srv/setup_db.py", line 18, in <module>
frontend_1    |     add_canary_nxdomain(domain=d)
frontend_1    |   File "/srv/queries.py", line 53, in add_canary_nxdomain
frontend_1    |     raise ValueError
frontend_1    | exceptions.ValueError:
```

**Comment by gabemarshall** [comment]
Turns out it was failing because I had left CANARY_NXDOMAINS blank in my frontend.env file. Whoops!
